-- WikiSprint uses Supabase Realtime Broadcast + Presence.
-- No database tables are required for the basic version.
-- In Supabase Dashboard:
-- 1. Create a project.
-- 2. Go to Project Settings > API.
-- 3. Copy the Project URL and anon/public key into config.js.
--
-- This app deliberately avoids storing player names or race results permanently.
-- Each room exists only while participants are connected.

-- Optional hardening if you later add a database:
-- Keep the database tables private and never expose service_role keys in browser code.
